### ISSUE TITLE
Why isn't there a minimize button!?

### ISSUE THREAD

**Issue by ricol03** [Dat-Dot/DatCalc#1]
Gimme a minimize button, onegaishimasu! 
![image](https://user-images.githubusercontent.com/87026265/135760337-be963636-ed63-4453-acf7-aa5596d1769a.png)

**Comment by ExistingPosition486** [comment]
Minimize button was accidentally removed. It will be fixed in the next release. Thank you for your feedback

**Comment by ricol03** [comment]
yw loli

**Comment by ExistingPosition486** [comment]
Your issue is resolved with v1.0.2_b1
Download it here for latest bug fixes: https://github.com/Dat-Dot/DatCalc/releases/tag/1.0.2_b1
